#!/bin/bash
# Получаем информацию об использовании памяти
MEMORY_USED=$(free -m | awk 'NR==2{printf "%.1f", $3/1024}')
MEMORY_TOTAL=$(free -m | awk 'NR==2{printf "%.1f", $2/1024}')
echo "$MEMORY_USED/$MEMORY_TOTAL GB"
