#!/bin/bash
INTERFACE=$(ip route | awk '/default/ {print $5}')
IP=$(ip addr show $INTERFACE | grep "inet " | awk '{print $2}' | cut -d/ -f1)
SSID=$(iwgetid -r)
if [ -z "$SSID" ]; then
    echo "Offline"
else
    echo "$SSID"
fi
